# Generated by Django 2.1.5 on 2019-01-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
